version: "3.8"

services:
  api:
    build: .
    container_name: auth-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=auth
      - DB_PASSWORD=123Abc
      - DB_NAME=auth
      - JWT_SECRET=2d7d9a87-9419-46c0-9c81-0f4c8ead48b0
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: 123Abc
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: