org: ${env:SERVERLESS_ORG_NAME}

service: auth-fast-food

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  environment:
    SLS_STAGE: ${self:provider.stage}
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    DB_PORT: ${env:DB_PORT}
    JWT_SECRET: ${env:JWT_SECRET}

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - NODE_ENV
      - AWS_REGION

functions:
  healthCheck:
    handler: src/controllers.healthCheck
    events:
      - httpApi:
          path: /health
          method: get
  login:
    handler: src/controllers.login
    events:
      - httpApi:
          path: /login
          method: post
